-- MySQL Script generated by MySQL Workbench
-- Wed May  5 12:29:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema monfauna
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema monfauna
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monfauna` DEFAULT CHARACTER SET utf8 ;
USE `monfauna` ;

-- -----------------------------------------------------
-- Table `monfauna`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monfauna`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `admin` TINYINT NOT NULL,
  `created_at` DATETIME NULL DEFAULT now(),
  `updated_at` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monfauna`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monfauna`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT now(),
  `updated_at` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monfauna`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monfauna`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `latitude` VARCHAR(255) NULL,
  `longitude` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monfauna`.`specie_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monfauna`.`specie_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monfauna`.`specie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monfauna`.`specie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `scientific_name` VARCHAR(45) NOT NULL,
  `common_name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL DEFAULT now(),
  `updated_at` DATETIME NULL DEFAULT now(),
  `specie_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Specie_Specie_Type1_idx` (`specie_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Specie_Specie_Type1`
    FOREIGN KEY (`specie_type_id`)
    REFERENCES `monfauna`.`specie_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monfauna`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monfauna`.`animal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(45) NULL,
  `sex` VARCHAR(1) NULL,
  `image_url` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL DEFAULT now(),
  `register_date` DATETIME NULL,
  `location_id` INT NULL,
  `project_id` INT NOT NULL,
  `specie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Animal_Location1_idx` (`location_id` ASC) VISIBLE,
  INDEX `fk_Animal_Project1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_Animal_Specie1_idx` (`specie_id` ASC) VISIBLE,
  CONSTRAINT `fk_Animal_Location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `monfauna`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `monfauna`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_Specie1`
    FOREIGN KEY (`specie_id`)
    REFERENCES `monfauna`.`specie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monfauna`.`animal_measurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monfauna`.`animal_measurement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `length` DOUBLE NULL,
  `width` DOUBLE NULL,
  `height` DOUBLE NULL,
  `weight` DOUBLE NULL,
  `description` VARCHAR(255) NOT NULL,
  `animal_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_animal_measurement_animal1_idx` (`animal_id` ASC) VISIBLE,
  CONSTRAINT `fk_animal_measurement_animal1`
    FOREIGN KEY (`animal_id`)
    REFERENCES `monfauna`.`animal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monfauna`.`user_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monfauna`.`user_project` (
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
  INDEX `fk_User_has_Project_Project1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_User_has_Project_User1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Project_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `monfauna`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Project_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `monfauna`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
