-- MySQL Script generated by MySQL Workbench
-- Thu May  6 14:09:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MonFauna
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MonFauna
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MonFauna` DEFAULT CHARACTER SET utf8 ;
USE `MonFauna` ;

-- -----------------------------------------------------
-- Table `MonFauna`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonFauna`.`user` (
                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                 `name` VARCHAR(100) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `admin` TINYINT NOT NULL,
    `created_at` DATETIME NULL DEFAULT now(),
    `updated_at` DATETIME NULL DEFAULT now(),
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MonFauna`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonFauna`.`project` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `name` VARCHAR(45) NULL,
    `created_at` DATETIME NULL DEFAULT now(),
    `updated_at` DATETIME NULL DEFAULT now(),
    `owner_user_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_project_user1_idx` (`owner_user_id` ASC) VISIBLE,
    CONSTRAINT `fk_project_user1`
    FOREIGN KEY (`owner_user_id`)
    REFERENCES `MonFauna`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MonFauna`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonFauna`.`location` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `name` VARCHAR(255) NOT NULL,
    `latitude` VARCHAR(255) NULL,
    `longitude` VARCHAR(255) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MonFauna`.`specie_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonFauna`.`specie_type` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MonFauna`.`specie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonFauna`.`specie` (
                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                   `scientific_name` VARCHAR(45) NOT NULL,
    `common_name` VARCHAR(45) NOT NULL,
    `created_at` DATETIME NULL DEFAULT now(),
    `updated_at` DATETIME NULL DEFAULT now(),
    `specie_type_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_Specie_Specie_Type1_idx` (`specie_type_id` ASC) VISIBLE,
    CONSTRAINT `fk_Specie_Specie_Type1`
    FOREIGN KEY (`specie_type_id`)
    REFERENCES `MonFauna`.`specie_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MonFauna`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonFauna`.`animal` (
                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                   `tag` VARCHAR(45) NULL,
    `sex` VARCHAR(1) NULL,
    `image_url` VARCHAR(255) NULL,
    `created_at` DATETIME NOT NULL DEFAULT now(),
    `updated_at` DATETIME NULL DEFAULT now(),
    `register_date` DATETIME NULL,
    `location_id` INT NULL,
    `project_id` INT NOT NULL,
    `specie_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_Animal_Location1_idx` (`location_id` ASC) VISIBLE,
    INDEX `fk_Animal_Project1_idx` (`project_id` ASC) VISIBLE,
    INDEX `fk_Animal_Specie1_idx` (`specie_id` ASC) VISIBLE,
    CONSTRAINT `fk_Animal_Location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `MonFauna`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Animal_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `MonFauna`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Animal_Specie1`
    FOREIGN KEY (`specie_id`)
    REFERENCES `MonFauna`.`specie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MonFauna`.`animal_measurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonFauna`.`animal_measurement` (
                                                               `id` INT NOT NULL AUTO_INCREMENT,
                                                               `length` DOUBLE NULL,
                                                               `width` DOUBLE NULL,
                                                               `height` DOUBLE NULL,
                                                               `weight` DOUBLE NULL,
                                                               `description` VARCHAR(255) NOT NULL,
    `animal_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_animal_measurement_animal1_idx` (`animal_id` ASC) VISIBLE,
    CONSTRAINT `fk_animal_measurement_animal1`
    FOREIGN KEY (`animal_id`)
    REFERENCES `MonFauna`.`animal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MonFauna`.`collaborator_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MonFauna`.`collaborator_project` (
                                                                 `user_id` INT NOT NULL,
                                                                 `project_id` INT NOT NULL,
                                                                 PRIMARY KEY (`user_id`, `project_id`),
    INDEX `fk_User_has_Project_Project1_idx` (`project_id` ASC) VISIBLE,
    INDEX `fk_User_has_Project_User1_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `fk_User_has_Project_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `MonFauna`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_User_has_Project_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `MonFauna`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
